### ISSUE TITLE
예시가 바뀌어야할 것 같아요!

### ISSUE THREAD

**Issue by gracefullight** [Joungkyun/font-d2coding-ligature#1]
서빙해주셔서 감사합니다.

그런데 예시가 바뀌어야할 것 같아요.

`https://cdn.jsdelivr.net/gh/joungkyun/font-d2coding-ligature@1.3.2/d2coding-ligature.css` 가 가져와지고

`https://cdn.jsdelivr.net/gh/joungkyun/font-d2coding-ligature@1.3.2/d2coding.css` 는 없다고 나옵니다! 😂

**Comment by Joungkyun** [comment]
@gracefullight reporting 감사합니다.
